[tool.autopep8]
max_line_length = 120
aggressive = 2

[tool.flake8]
max-line-length = 120
max-complexity = 12
doctests = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
